In [2]:
import pandas as pd
df = pd.read_csv("C:/Users\monster\Desktop\Regresyon Modelleri\MultipleLinearRegression\Advertising.csv")
df = df.iloc[:,1:len(df)]
X = df.drop('sales', axis = 1)
y = df[["sales"]]
import statsmodels.api as sm
lm = sm.OLS(y, X)
model = lm.fit()
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(X, y)
model.intercept_


array([2.93888937])

In [3]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

PREDICTION

Sales = 2.94 + TV* 0.04 + radio* 0.19 - newspaper* 0.001  <- Avarage


In [5]:
new_data = [[30],[10],[40]]
new_data = pd.DataFrame(new_data).T
new_data

0   1   2
0  30  10  40

In [6]:
model.predict(new_data)

array([[6.15562918]])

In [8]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [12]:
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697